### ISSUE TITLE
Make user handles clickable in FA owners doc

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-contributor-docs#14]
See https://github.com/strongloop/loopback-contributor-docs/pull/13#issuecomment-250387220

**Comment by superkhau** [comment]
@bajtos Where should the username links go to? GH profile?

**Comment by Amir-61** [comment]
Closing as done:
https://github.com/strongloop/loopback-contributor-docs/pull/16
https://github.com/strongloop/loopback-contributor-docs/pull/16
